baseURL = 'https://marsomarwa.github.io/'
title = 'Marwa Marso'
languageCode = 'en-us'
theme = 'barks'

[params]
    [params.head]
        author = "Marwa Marso"
        description = "Hi, I'm Marwa, welcome to my website!"
        keywords = ["some", "keywords", "to", "describe", "this"]
    
    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:m.marso@nus.edu.sg"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/marwamarso/"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=eV1dyrMAAAAJ&hl=en"
            weight = 3
        [params.social.goodreads]
            name = "Goodreads"
            class = "fab fa-goodreads"
            url = "https://www.goodreads.com/list/show/203651.Curated_list_of_books_that_shaped_me"
            weight = 4
    
    [params.navigation]
        show_navigation = true
    [params.footer]
        show_footer = true
    


    [params.colors]
        theme_color       = "#328e13"   # primary accent — nature and vitality
        background_color  = "#fdfdfb"   # almost white to let the accents breathe
        text_color        = "#222824"   # dark olive-gray for grounded contrast
        link_color        = "#ff616b"   # your original coral — lively but sparing
        accent_color      = "#a6e6db"   # pale sea-mint for highlights or hover


    [params.colors_dark]
        theme_color       = "#a6e6db"
        background_color  = "#172713"
        text_color        = "#f1f1f0"
        link_color        = "#ff616b"
        accent_color      = "#4bbf73"



[menus]
    [[menu.main]]
        identifier = "About"
        name = "About"
        url = "/About/"
        weight = 1
    [[menu.main]]
        identifier = "Research"
        name = "Research"
        url = "/Research/"
        weight = 2
    [[menu.main]]
        identifier = "Random"
        name = "Random"
        url = "/Random/"
        weight = 3

